### ISSUE TITLE
`hoster vm disk-expand` error

### ISSUE THREAD

**Issue by leyoda** [yaroslav-gwit/HosterCore#5]
The bug happens when you try to expand a disk of the VM that does not exist or it's name is misspelled.

The error return is not handled and we get the following message: 
```
vmConfig Function Error: open /vm_config.json: no such file or directory
panic: unexpected end of JSON input

goroutine 1 [running]:
hoster/cmd.vmConfig({_, _})
	/root/Git/HosterCore/cmd/vm_list.go:265 +0x14b
hoster/cmd.diskExpandOffline({0x820da82f6, 0x4}, {0x9bf600, 0x9}, 0x0?)
	/root/Git/HosterCore/cmd/vm_disk_expand.go:34 +0x7b
hoster/cmd.glob..func17(0xe715e0?, {0x850203050?, 0x3?, 0x3?})
	/root/Git/HosterCore/cmd/vm_disk_expand.go:24 +0x46
github.com/spf13/cobra.(*Command).execute(0xe715e0, {0x850203020, 0x3, 0x3})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).executeC(0xe71d60)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
hoster/cmd.Execute()
	/root/Git/HosterCore/cmd/root.go:21 +0x25
main.main()
	/root/Git/HosterCore/main.go:9 +0x17
```

On the other commands it works, we have the return of the type VM is not found in the system.

**Comment by yaroslav-gwit** [comment]
Issue was fixed by swapping around the code lines:
from
```
	vmFolder := getVmFolder(vmName)
	vmConfigVar := vmConfig(vmName)
	allVms := getAllVms()
	if slices.Contains(allVms, vmName) {
		_ = 0
	} else {
		return errors.New("vm was not found")
	}

	if vmLiveCheck(vmName) {
		return errors.New("vm has to be offline, due to the data loss possibility of online expansion")
	}
```

to
```
	allVms := getAllVms()
	if slices.Contains(allVms, vmName) {
		_ = 0
	} else {
		return errors.New("vm was not found")
	}

	vmFolder := getVmFolder(vmName)
	vmConfigVar := vmConfig(vmName)
	if vmLiveCheck(vmName) {
		return errors.New("vm has to be offline, due to the data loss possibility of online expansion")
	}
```

This was a problem, because the function tried to load VMs config file, before it checked if VM exists.
