### ISSUE TITLE
`hoster vm secrets` doesn't check if VM exists

### ISSUE THREAD

**Issue by yaroslav-gwit** [yaroslav-gwit/HosterCore#50]
Somehow I failed to implement a basic `vm exists` check in the last `hoster vm secrets` implementation, which needs to be fixed now. In case you'd call the command below and use a VM name that is not present on a given system, it panics:

(command)
```shell
hoster vm secrets nonExistentVm
```

(output)
```
mConfig Function Error:  open /vm_config.json: no such file or directory
panic: unexpected end of JSON input

goroutine 1 [running]:
hoster/cmd.vmConfig({_, _})
        /root/Git/HosterCore/cmd/vm_list.go:283 +0x14b
hoster/cmd.vmSecretsTableOutput({0x820f41d0a, 0x9})
        /root/Git/HosterCore/cmd/vm_secrets.go:36 +0x3e
hoster/cmd.glob..func39(0xe54fa0?, {0x85006d750, 0x1, 0x1?})
        /root/Git/HosterCore/cmd/vm_secrets.go:27 +0x85
github.com/spf13/cobra.(*Command).execute(0xe54fa0, {0x85006d720, 0x1, 0x1})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xe54320)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
hoster/cmd.Execute()
        /root/Git/HosterCore/cmd/root.go:28 +0x25
main.main()
        /root/Git/HosterCore/main.go:9 +0x17
```

**Comment by yaroslav-gwit** [comment]
The bug has been fixed by implementing the VM exists
