### ISSUE TITLE
Change `cpu_cores`, `cpu_sockets` and `vnc_port` config keys from `string` to `int`

### ISSUE THREAD

**Issue by yaroslav-gwit** [yaroslav-gwit/HosterCore#90]
After implementing `cpu_threads` as `int`, I need to fix the `cpu_cores` and `cpu_sockets` keys to be `int`s too in order to stay consistent.

So essentially, we need to migrate from this:
```json
   "cpu_sockets": "1",
   "cpu_cores": "2",
   "cpu_threads": 2,
```

To this:
```json
   "cpu_sockets": 1,
   "cpu_cores": 2,
   "cpu_threads": 2,
```

For this purpose I'll implement the config migration utility, so whenever you install a new `Hoster` version you'll have the ability to simply call `hoster config-migrate` and fix all your VM configs inconsistencies (yes, the old file will be backed up just in case).

Some of you may be wondering "why is this change required in the first place?". The short answer is: `Go` is automatically type checking every field it imports from the `JSON` config file - so we can't simply change the key type and expect a miracle to happen. Instead a panic will occur:
```log
panic: json: cannot unmarshal number into Go struct field VmConfigStruct.cpu_cores of type string

goroutine 1 [running]:
HosterCore/cmd.vmConfig({_, _})
	/root/Git/HosterCore/cmd/vm_list.go:308 +0x14b
HosterCore/cmd.generateBhyveStartCommand({0x820c81988, 0x9}, 0x0, 0x0, 0x1)
	/root/Git/HosterCore/cmd/vm_start.go:88 +0x55
HosterCore/cmd.VmStart({0x820c81988, 0x9}, 0x0?, 0x0?, 0x1)
	/root/Git/HosterCore/cmd/vm_start.go:56 +0x146
HosterCore/cmd.glob..func74(0xbadba0?, {0x850076820, 0x1, 0x2?})
	/root/Git/HosterCore/cmd/vm_start.go:36 +0x85
github.com/spf13/cobra.(*Command).execute(0xbadba0, {0x850076800, 0x2, 0x2})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xbac520)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
HosterCore/cmd.Execute()
	/root/Git/HosterCore/cmd/main.go:29 +0x25
main.main()
	/root/Git/HosterCore/main.go:9 +0x17

```

**Comment by yaroslav-gwit** [comment]
This is now done, using a helper function that normalises the input data (if there is a need for it). Here is a reference implementation.

Try reading a VM config file, but normalise it if `json` could not be un-marshalled normally:
```go
data, err := os.ReadFile(vmConfLocation)
if err != nil {
	e = err
	return
}

err = json.Unmarshal(data, &r)
if err != nil {
	r, e = FixVmConfig(vmConfLocation)
	return
}

return
```

Normalise the data, if there is a need for it:
```go
func FixVmConfig(vmConfLocation string) (r VmConfig, e error) {
	if !FileExists.CheckUsingOsStat(vmConfLocation) {
		e = errors.New("vm config file could not be found here: " + vmConfLocation)
		return
	}

	oldConfig := make(map[string]any)
	data, err := os.ReadFile(vmConfLocation)
	if err != nil {
		e = err
		return
	}

	err = json.Unmarshal(data, &oldConfig)
	if err != nil {
		e = err
		return
	}

	cpuSockets, exist := oldConfig["cpu_sockets"]
	if exist && reflect.TypeOf(cpuSockets) == reflect.TypeOf("string") {
		parsedInt, err := strconv.Atoi(fmt.Sprintf("%s", cpuSockets))
		if err != nil {
			e = err
			return
		}
		oldConfig["cpu_sockets"] = parsedInt
	}

	cpuCores, exist := oldConfig["cpu_cores"]
	if exist && reflect.TypeOf(cpuCores) == reflect.TypeOf("string") {
		parsedInt, err := strconv.Atoi(fmt.Sprintf("%s", cpuCores))
		if err != nil {
			e = err
			return
		}
		oldConfig["cpu_cores"] = parsedInt
	}

	cpuThreads, exist := oldConfig["cpu_threads"]
	if exist && reflect.TypeOf(cpuThreads) == reflect.TypeOf("string") {
		parsedInt, err := strconv.Atoi(fmt.Sprintf("%s", cpuThreads))
		if err != nil {
			e = err
			return
		}
		oldConfig["cpu_threads"] = parsedInt
	}

	vncPort, exist := oldConfig["vnc_port"]
	if exist && reflect.TypeOf(vncPort) == reflect.TypeOf("string") {
		parsedInt, err := strconv.Atoi(fmt.Sprintf("%s", vncPort))
		if err != nil {
			e = err
			return
		}
		oldConfig["vnc_port"] = parsedInt
	}

	prod, exist := oldConfig["live_status"]
	if exist && reflect.TypeOf(prod) == reflect.TypeOf("string") {
		parsed := fmt.Sprintf("%s", prod)
		if parsed == "production" || parsed == "prod" {
			oldConfig["production"] = true
		}
	}

	m, err := json.Marshal(oldConfig)
	if err != nil {
		e = err
		return
	}

	err = json.Unmarshal(m, &r)
	if err != nil {
		e = err
		return
	}

	return
}
```
